Repository side-peek/sidepeek_backend, pull requests merged in 2024-03, with the labels that each got.

#83 깃허브 액션 에러 해결 테스트
  .github/workflows/ci.yml
Labels: ⚙️ 세팅했슈, 🛠 리팩토링했슈, ✅ 테스트혀봤슈

#75 커스텀 에러 코드 적용(User)
  src/main/java/sixgaezzang/sidepeek/users/domain/Password.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/exception/UserErrorCode.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Labels: 🛠 리팩토링했슈, 🌳 밥 좀 드셔유

#71 프로젝트 저장 유효성 검사 완료 및 테스트 코드 일부 작성
  src/main/generated/sixgaezzang/sidepeek/projects/domain/QProject.java
  src/main/java/sixgaezzang/sidepeek/common/util/CommonConstant.java
  src/main/java/sixgaezzang/sidepeek/common/util/Regex.java
  src/main/java/sixgaezzang/sidepeek/common/util/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/ProjectSkill.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/file/File.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/member/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/MemberSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSkillSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/service/FileService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/ProjectConstant.java
  src/main/java/sixgaezzang/sidepeek/projects/util/converter/YearMonthDateAttributeConverter.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/FileValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectSkillValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectValidator.java
  src/main/java/sixgaezzang/sidepeek/skill/util/validation/SkillValidator.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/sixgaezzang/sidepeek/projects/service/FileServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
Labels: 🚀 더 만들어봤슈, 🛠 리팩토링했슈, ✅ 테스트혀봤슈

#76 프로젝트 생성 테스트 코드 작성 및 에러 메시지 정의
  src/main/java/sixgaezzang/sidepeek/projects/domain/file/File.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/member/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/FileErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/ProjectErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/ProjectSkillErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/ProjectConstant.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/FileValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectSkillValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectValidator.java
  src/main/java/sixgaezzang/sidepeek/skill/util/validation/SkillErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/skill/util/validation/SkillValidator.java
  src/test/java/sixgaezzang/sidepeek/projects/service/FileServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeDtoProvider.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeEntityProvider.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeValueProvider.java
  src/test/java/sixgaezzang/sidepeek/projects/util/TestParameterProvider.java
Labels: ✅ 테스트혀봤슈

#81 프로젝트 저장/수정/삭제 api 스웨거 적용
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/MemberSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSkillSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/OverviewImageSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectSkillSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/response/SkillResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeDtoProvider.java
Labels: 🚀 더 만들어봤슈, 🌳 밥 좀 드셔유

#82 프로젝트 댓글 저장/수정/삭제/조회(목록) api 컨트롤러 및 스웨거 설정
  src/main/java/sixgaezzang/sidepeek/comments/controller/CommentController.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/request/CommentRequest.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentListResponse.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentResponse.java
  src/main/java/sixgaezzang/sidepeek/comments/exception/message/CommentErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/comments/util/CommentConstant.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectValidator.java
  src/test/java/sixgaezzang/sidepeek/projects/service/FileServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
Labels: 🚀 더 만들어봤슈, 🌳 밥 좀 드셔유

#87 회원 프로필 조회/수정 및 비밀번호 수정 api 스웨거 설정
  src/main/java/sixgaezzang/sidepeek/common/exception/message/CommonErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/member/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/MemberSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/ProjectErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectValidator.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckNicknameRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/SignUpRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdatePasswordRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserProfileRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserSkillRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSkillSummary.java
  src/main/java/sixgaezzang/sidepeek/users/exception/UserErrorCode.java
  src/main/java/sixgaezzang/sidepeek/users/exception/message/UserErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/main/java/sixgaezzang/sidepeek/users/util/UserConstant.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeValueProvider.java
  src/test/java/sixgaezzang/sidepeek/projects/util/TestParameterProvider.java
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Labels: 🚀 더 만들어봤슈

#103 미디어 저장(S3) api 회원 확인 로직 추가
  src/main/java/sixgaezzang/sidepeek/common/util/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/config/S3Config.java
  src/main/java/sixgaezzang/sidepeek/config/properties/S3Properties.java
  src/main/java/sixgaezzang/sidepeek/media/controller/MediaController.java
  src/main/java/sixgaezzang/sidepeek/media/exception/MediaExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/media/exception/message/MediaErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/media/service/MediaService.java
  src/main/java/sixgaezzang/sidepeek/media/util/MediaConstant.java
  src/main/java/sixgaezzang/sidepeek/media/util/validation/MediaValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/test/java/sixgaezzang/sidepeek/media/service/MediaServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeValueProvider.java
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Labels: 🚀 더 만들어봤슈, 🛠 리팩토링했슈, ✅ 테스트혀봤슈

#93 프로젝트 전체 조회 api 구현
  src/main/generated/sixgaezzang/sidepeek/like/domain/QLike.java
  src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java
  src/main/java/sixgaezzang/sidepeek/like/domain/Like.java
  src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepository.java
  src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectListResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/ProjectRepository.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/ProjectRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/ProjectRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/resources/db/data/afterMigrate.sql
Labels: 🚀 더 만들어봤슈

#92 깃허브 로그인
  build.gradle
  src/main/generated/sixgaezzang/sidepeek/auth/domain/QAuthProvider.java
  src/main/java/sixgaezzang/sidepeek/auth/domain/AuthProvider.java
  src/main/java/sixgaezzang/sidepeek/auth/domain/ProviderType.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/OAuth2UserImpl.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/response/SocialLoginResponse.java
  src/main/java/sixgaezzang/sidepeek/auth/jwt/JWTManager.java
  src/main/java/sixgaezzang/sidepeek/auth/repository/AuthProviderRepository.java
  src/main/java/sixgaezzang/sidepeek/auth/repository/AuthProviderRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/auth/repository/AuthProviderRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java
  src/main/java/sixgaezzang/sidepeek/auth/service/OAuth2LoginSuccessHandler.java
  src/main/java/sixgaezzang/sidepeek/auth/service/OAuth2UserServiceImpl.java
  src/main/java/sixgaezzang/sidepeek/auth/service/strategy/GithubUserInfoMapper.java
  src/main/java/sixgaezzang/sidepeek/auth/service/strategy/UserInfoMapper.java
  src/main/java/sixgaezzang/sidepeek/auth/service/strategy/UserInfoMapperFactory.java
  src/main/java/sixgaezzang/sidepeek/config/PasswordEncoderConfig.java
  src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
  src/main/java/sixgaezzang/sidepeek/users/domain/Password.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/exception/UserErrorCode.java
  src/main/java/sixgaezzang/sidepeek/users/exception/message/UserErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/main/java/sixgaezzang/sidepeek/users/util/UserConstant.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__init.sql
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Labels: 🚀 더 만들어봤슈, 🥕 더 수정해봤슈

#105 프로젝트 저장 및 수정에서 회원인 멤버도 닉네임 자유롭게 쓰도록 설정
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/member/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveMemberRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectSkillRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/MemberRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectSkillValidator.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/main/java/sixgaezzang/sidepeek/users/util/validation/UserValidator.java
  src/main/resources/db/migration/V2__not_null_member_nickname.sql
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeDtoProvider.java
  src/test/java/sixgaezzang/sidepeek/projects/util/FakeEntityProvider.java
  src/test/java/sixgaezzang/sidepeek/projects/util/TestParameterProvider.java
Labels: 🐛 아이고 벌레!, 🛠 리팩토링했슈, 🥕 더 수정해봤슈

#121 스웨거 리팩토링
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  src/main/java/sixgaezzang/sidepeek/auth/controller/AuthController.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/request/LoginRequest.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/request/ReissueTokenRequest.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/response/LoginResponse.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/response/SocialLoginResponse.java
  src/main/java/sixgaezzang/sidepeek/auth/exeption/message/AuthErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/comments/controller/CommentController.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/request/CommentRequest.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentResponse.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/ReplyResponse.java
  src/main/java/sixgaezzang/sidepeek/common/doc/AuthControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/CommentControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/MediaControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/SkillControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/UserControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/exception/ErrorResponse.java
  src/main/java/sixgaezzang/sidepeek/config/SwaggerConfig.java
  src/main/java/sixgaezzang/sidepeek/media/controller/MediaController.java
  src/main/java/sixgaezzang/sidepeek/media/dto/response/MediaUploadResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveMemberRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectSkillRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectSkillSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/response/SkillSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/skill/exception/message/SkillErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckEmailRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckNicknameRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/SignUpRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdatePasswordRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserProfileRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserSkillRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/CheckDuplicateResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSkillSummary.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/main/java/sixgaezzang/sidepeek/users/exception/message/UserErrorMessage.java
Labels: ✏️ 기록혀야쥬, 🛠 리팩토링했슈, 🥕 더 수정해봤슈

#116 XXXValidator static import 로 변경
  src/main/java/sixgaezzang/sidepeek/comments/exception/message/CommentErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/comments/util/CommentConstant.java
  src/main/java/sixgaezzang/sidepeek/common/dto/request/UpdateUserSkillRequest.java
  src/main/java/sixgaezzang/sidepeek/common/exception/message/CommonErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/common/util/CommonConstant.java
  src/main/java/sixgaezzang/sidepeek/common/util/Regex.java
  src/main/java/sixgaezzang/sidepeek/common/util/SetUtils.java
  src/main/java/sixgaezzang/sidepeek/common/util/validation/TechStackValidator.java
  src/main/java/sixgaezzang/sidepeek/common/util/validation/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/media/exception/message/MediaErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/media/service/MediaService.java
  src/main/java/sixgaezzang/sidepeek/media/util/MediaConstant.java
  src/main/java/sixgaezzang/sidepeek/media/util/validation/MediaValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/ProjectSkill.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/file/File.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/member/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/FileErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/ProjectErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/service/FileService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/ProjectConstant.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/FileValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectSkillValidator.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/ProjectValidator.java
  src/main/java/sixgaezzang/sidepeek/skill/domain/Skill.java
  src/main/java/sixgaezzang/sidepeek/skill/exception/message/SkillErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/skill/serivce/SkillService.java
  src/main/java/sixgaezzang/sidepeek/skill/util/validation/SkillValidator.java
  src/main/java/sixgaezzang/sidepeek/users/domain/Password.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/domain/UserSkill.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserProfileRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserSkillRequest.java
  src/main/java/sixgaezzang/sidepeek/users/exception/message/UserErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserSkillService.java
  src/main/java/sixgaezzang/sidepeek/users/util/UserConstant.java
  src/main/java/sixgaezzang/sidepeek/users/util/validation/UserSkillValidator.java
  src/main/java/sixgaezzang/sidepeek/users/util/validation/UserValidator.java
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/users/service/UserSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/util/FakeDtoProvider.java
Labels: 🛠 리팩토링했슈

#125 afterMigrate.sql 설정에 스킬 데이터 21개 추가
  src/main/resources/db/data/afterMigrate.sql
Labels: ⚙️ 세팅했슈

#137 기술 스택 검색, 회원 닉네임 검색 에러 해결 #132
  src/main/java/sixgaezzang/sidepeek/common/doc/SkillControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/UserControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
Labels: 🐛 아이고 벌레!, 🚨 돌 굴러가유, 🥕 더 수정해봤슈

#119 기술스택과 멤버 중복 검사 로직 구현
  src/main/java/sixgaezzang/sidepeek/common/dto/request/SaveTechStackRequest.java
  src/main/java/sixgaezzang/sidepeek/common/exception/message/CommonErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/common/exception/message/TechStackErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/common/util/validation/TechStackValidator.java
  src/main/java/sixgaezzang/sidepeek/common/util/validation/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserProfileRequest.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserSkillService.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
  src/test/java/sixgaezzang/sidepeek/users/service/UserSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/util/FakeDtoProvider.java
  src/test/java/sixgaezzang/sidepeek/util/TestParameterProvider.java
Labels: 🐛 아이고 벌레!, 🛠 리팩토링했슈, ✅ 테스트혀봤슈

#145 UserSummary, UserProfileResponse에 isSocialLogin 추가
  src/main/java/sixgaezzang/sidepeek/auth/repository/AuthProviderRepository.java
  src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/main/java/sixgaezzang/sidepeek/users/exception/message/UserErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java
Labels: 🚀 더 만들어봤슈, 🛠 리팩토링했슈

#135 댓글 CUD api 구현
  src/main/java/sixgaezzang/sidepeek/comments/controller/CommentController.java
  src/main/java/sixgaezzang/sidepeek/comments/domain/Comment.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/request/SaveCommentRequest.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/request/UpdateCommentRequest.java
  src/main/java/sixgaezzang/sidepeek/comments/exception/message/CommentErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/comments/service/CommentService.java
  src/main/java/sixgaezzang/sidepeek/comments/util/CommentConstant.java
  src/main/java/sixgaezzang/sidepeek/comments/util/validation/CommentValidator.java
  src/main/java/sixgaezzang/sidepeek/common/doc/CommentControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/common/exception/InvalidAuthorityException.java
  src/main/java/sixgaezzang/sidepeek/common/util/validation/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/resources/db/migration/V3__delete_cascade_comment.sql
  src/test/java/sixgaezzang/sidepeek/comments/service/CommentServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/util/FakeDtoProvider.java
  src/test/java/sixgaezzang/sidepeek/util/FakeEntityProvider.java
  src/test/java/sixgaezzang/sidepeek/util/FakeValueProvider.java
  src/test/java/sixgaezzang/sidepeek/util/TestParameterProvider.java
Labels: 🚀 더 만들어봤슈, ✅ 테스트혀봤슈

#148 사용자 관련(참여한/좋아요 한/댓글 단) 프로젝트 조회 기능 구현
  src/main/java/sixgaezzang/sidepeek/common/doc/UserControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/dto/response/Page.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/UserProjectSearchType.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/ProjectErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/ProjectRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/ProjectRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/util/FakeEntityProvider.java
  src/test/java/sixgaezzang/sidepeek/util/FakeValueProvider.java
Labels: 🚀 더 만들어봤슈

#151 프로젝트 상세 조회 시 누락된 댓글 수 및 댓글 관련 응답 객체 수정
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentWithCountResponse.java
  src/main/java/sixgaezzang/sidepeek/comments/service/CommentService.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
Labels: 🛠 리팩토링했슈, 🥕 더 수정해봤슈

#149 프로젝트 조회 시 다중 필터 및 커서 기반 페이지네이션 적용
  src/main/java/sixgaezzang/sidepeek/comments/service/CommentService.java
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/like/service/LikeService.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/CursorPaginationInfoRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SortType.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/CursorPaginationResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectListResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/member/MemberRepository.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/member/MemberRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/member/MemberRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepository.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/sixgaezzang/sidepeek/comments/service/CommentServiceTest.java
  src/test/java/sixgaezzang/sidepeek/like/service/LikeServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/FileServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
Labels: 🚀 더 만들어봤슈, 🛠 리팩토링했슈, 🚨 돌 굴러가유, 🥕 더 수정해봤슈

#147 지난 주 인기 프로젝트 목록 조회(배너용) 구현
  src/main/java/sixgaezzang/sidepeek/auth/dto/request/LoginRequest.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/request/ReissueTokenRequest.java
  src/main/java/sixgaezzang/sidepeek/auth/exception/message/AuthErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/common/exception/InvalidAuthorityException.java
  src/main/java/sixgaezzang/sidepeek/common/util/component/DateTimeProvider.java
  src/main/java/sixgaezzang/sidepeek/common/util/validation/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectBannerResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/DateUtils.java
  src/main/java/sixgaezzang/sidepeek/projects/util/ProjectConstant.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/test/java/sixgaezzang/sidepeek/comments/service/CommentServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/util/FakeEntityProvider.java
Labels: ✏️ 기록혀야쥬, 🚀 더 만들어봤슈

#161 옵션 값이 있는 요청, 응답에서 값이 빈 경우 타입 통일
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/main/resources/db/data/afterMigrate.sql
Labels: 🛠 리팩토링했슈

#164 댓글 생성 및 삭제 시 댓글 수 업데이트 안 되는 버그 해결
  config/checkstyle/suppressions.xml
  src/main/java/sixgaezzang/sidepeek/comments/domain/Comment.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentWithCountResponse.java
  src/main/java/sixgaezzang/sidepeek/comments/repository/CommentRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/comments/repository/CommentRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/comments/service/CommentService.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V4__add_project_commentCount.sql
  src/test/java/sixgaezzang/sidepeek/comments/service/CommentServiceTest.java
Labels: 🐛 아이고 벌레!, 😇 아이고 숨이 맥혀..., 🛠 리팩토링했슈

#172 프로젝트 상세 조회 시 응답에 좋아요 Id 추가
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java
  src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/like/repository/LikeRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
Labels: ✏️ 기록혀야쥬, 🛠 리팩토링했슈, 🥕 더 수정해봤슈, ✅ 테스트혀봤슈

#170 스웨거에 로직, 유효성 검사 설명 추가하기
  src/main/java/sixgaezzang/sidepeek/comments/dto/request/SaveCommentRequest.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/request/UpdateCommentRequest.java
  src/main/java/sixgaezzang/sidepeek/comments/dto/response/CommentResponse.java
  src/main/java/sixgaezzang/sidepeek/common/doc/AuthControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/CommentControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/LikeControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/MediaControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/SkillControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/UserControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/description/CommentDescription.java
  src/main/java/sixgaezzang/sidepeek/common/doc/description/CommonDescription.java
  src/main/java/sixgaezzang/sidepeek/common/doc/description/ProjectDescription.java
  src/main/java/sixgaezzang/sidepeek/common/doc/description/SkillDescription.java
  src/main/java/sixgaezzang/sidepeek/common/doc/description/UserDescription.java
  src/main/java/sixgaezzang/sidepeek/common/dto/request/SaveTechStackRequest.java
  src/main/java/sixgaezzang/sidepeek/common/dto/response/Page.java
  src/main/java/sixgaezzang/sidepeek/like/dto/request/LikeRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/CursorPaginationInfoRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveMemberRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/SaveProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/UpdateProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/CursorPaginationResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectBannerResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectListResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectResponse.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/response/SkillSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckEmailRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/CheckNicknameRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/SignUpRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdatePasswordRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/request/UpdateUserProfileRequest.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserProfileResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/main/resources/banner.txt
Labels: ✏️ 기록혀야쥬, 🛠 리팩토링했슈

#178 사용하지 않는 fileType 필드 제거
  src/main/java/sixgaezzang/sidepeek/projects/domain/file/File.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/file/FileType.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/FileRepository.java
  src/main/java/sixgaezzang/sidepeek/projects/service/FileService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V5__delete_file_type.sql
  src/test/java/sixgaezzang/sidepeek/projects/service/FileServiceTest.java
Labels: 🛠 리팩토링했슈

#191 프로젝트 전체 조회 시 기술 스택 및 제목과 멤버로 검색 기능
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/doc/description/ProjectDescription.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/FindProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/resources/db/data/afterMigrate.sql
Labels: 🛠 리팩토링했슈, 🚨 돌 굴러가유, 🥕 더 수정해봤슈

#200 프로젝트 수정 후 댓글도 불러오도록 수정
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
Labels: 🛠 리팩토링했슈, 🚨 돌 굴러가유

#203 프로젝트 상세 조회 시 조회수 어뷰징 버그 해결
  src/main/java/sixgaezzang/sidepeek/common/annotation/Ip.java
  src/main/java/sixgaezzang/sidepeek/common/doc/ProjectControllerDoc.java
  src/main/java/sixgaezzang/sidepeek/common/resolver/IpArgumentResolver.java
  src/main/java/sixgaezzang/sidepeek/config/RedisConfig.java
  src/main/java/sixgaezzang/sidepeek/config/WebConfig.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
Labels: 🐛 아이고 벌레!, ✏️ 기록혀야쥬, 🚨 돌 굴러가유

#210 HttpRequestMethodNotSupportedException 핸들러 구현
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
Labels: 🚀 더 만들어봤슈

#211 Slack 메시지에 요청 url과 메서드 확인할 수 있도록 구현
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/common/util/component/SlackClient.java
  src/main/java/sixgaezzang/sidepeek/media/exception/MediaExceptionHandler.java
Labels: 🚀 더 만들어봤슈, 🛠 리팩토링했슈

#219 cors 에러 해결를 위한 설정 추가
  src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
Labels: ⚙️ 세팅했슈, 🚨 돌 굴러가유

#223 회원 소개글 최대 길이 설정 DB와 서버 같도록 수정
  src/main/java/sixgaezzang/sidepeek/users/util/UserConstant.java
Labels: 🐛 아이고 벌레!, 🚨 돌 굴러가유

#228 프로젝트 키워드로 검색 시 기술 스택으로 필터링 가능하도록 수정
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/FindProjectRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/project/ProjectRepositoryCustomImpl.java
Labels: 🛠 리팩토링했슈

#233 NPE 핸들러 구현
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/projects/exception/message/MemberErrorMessage.java
  src/main/java/sixgaezzang/sidepeek/projects/util/validation/MemberValidator.java
Labels: 🐛 아이고 벌레!

#235 프로젝트 기술 스택 및 멤버 카테고리 별로 조회되도록 응답 객체 수정
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/ProjectSkillSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/MemberRepository.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/member/MemberRepositoryCustom.java
  src/main/java/sixgaezzang/sidepeek/projects/repository/member/MemberRepositoryCustomImpl.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/test/java/sixgaezzang/sidepeek/projects/service/MemberServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectServiceTest.java
  src/test/java/sixgaezzang/sidepeek/projects/service/ProjectSkillServiceTest.java
  src/test/java/sixgaezzang/sidepeek/util/FakeValueProvider.java
Labels: 🛠 리팩토링했슈, ✅ 테스트혀봤슈

#244 dev 브랜치와 main 브랜치 충돌 해결
  .github/pull_request_template.md
Labels: ⚙️ 세팅했슈, ✅ 테스트혀봤슈
