Repository side-peek/sidepeek_backend, pull requests merged in 2024-02, with the labels that each got.

#13 데이터베이스 도커 설정
  .github/ISSUE_TEMPLATE/✨-이슈-템플릿.md
  .gitignore
  build.gradle
  docker/docker-compose.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: ⚙️ 세팅했슈

#14 Chore/#06 setup checkstyle
  .editorconfig
  .gitignore
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/sixgaezzang/sidepeek/SidepeekApplication.java
  src/test/java/sixgaezzang/sidepeek/SidepeekApplicationTests.java
Labels: ⚙️ 세팅했슈

#16 Flyway 설정
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/db/data/data.sql
  src/main/resources/db/migration/V1__init.sql
Labels: ⚙️ 세팅했슈

#20 자동 PR 리뷰어 설정
  .github/CODEOWNERS
Labels: ⚙️ 세팅했슈

#18 Jacoco 세팅
  build.gradle
  lombok.config
Labels: ⚙️ 세팅했슈

#22 민감 정보 관리를 위한 서브모듈 도입
  .gitignore
  .gitmodules
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: ⚙️ 세팅했슈

#26 Feat/#04 create project
  src/main/java/sixgaezzang/sidepeek/common/domain/BaseTimeEntity.java
  src/main/java/sixgaezzang/sidepeek/common/domain/Skill.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/AuthorityType.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/File.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/FileType.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/ProjectSkill.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/domain/UserSkill.java
  src/main/resources/db/migration/V1__init.sql
Labels: 🚀 더 만들어봤슈, ⚙️ 세팅했슈, 🛠 리팩토링했슈

#32 회원가입 기능 구현
  build.gradle
  src/main/java/sixgaezzang/sidepeek/common/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/main/java/sixgaezzang/sidepeek/users/domain/LoginType.java
  src/main/java/sixgaezzang/sidepeek/users/domain/Password.java
  src/main/java/sixgaezzang/sidepeek/users/domain/Provider.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
  src/main/java/sixgaezzang/sidepeek/users/dto/SignUpRequest.java
  src/main/java/sixgaezzang/sidepeek/users/repository/UserRepository.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
  src/main/resources/application.yml
Labels: 🚀 더 만들어봤슈

#35 Provider @Enumerated(EnumType.STRING) 긴급 설정
  build.gradle
  src/main/java/sixgaezzang/sidepeek/projects/domain/ProjectSkill.java
  src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java
  src/main/java/sixgaezzang/sidepeek/skill/domain/Skill.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/SkillResponse.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/SkillSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/skill/repository/SkillRepository.java
  src/main/java/sixgaezzang/sidepeek/skill/serivce/SkillService.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/main/java/sixgaezzang/sidepeek/users/domain/UserSkill.java
  src/main/java/sixgaezzang/sidepeek/users/dto/UserSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/UserSummaryResponse.java
  src/main/java/sixgaezzang/sidepeek/users/repository/UserRepository.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
Labels: 🐛 아이고 벌레!

#37 User 클래스에서 Provider 필드 @Enumerated(EnumType.STRING) 설정
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
Labels: 🐛 아이고 벌레!

#41 스웨거 설정
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/sixgaezzang/sidepeek/config/SwaggerConfig.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
Labels: 🚀 더 만들어봤슈, ⚙️ 세팅했슈

#39 기술 스택 및 회원 닉네임 검색 api 구현
  src/main/java/sixgaezzang/sidepeek/projects/domain/ProjectSkill.java
  src/main/java/sixgaezzang/sidepeek/skill/controller/SkillController.java
  src/main/java/sixgaezzang/sidepeek/skill/domain/Skill.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/SkillResponse.java
  src/main/java/sixgaezzang/sidepeek/skill/dto/SkillSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/skill/repository/SkillRepository.java
  src/main/java/sixgaezzang/sidepeek/skill/serivce/SkillService.java
  src/main/java/sixgaezzang/sidepeek/users/controller/UserController.java
  src/main/java/sixgaezzang/sidepeek/users/domain/UserSkill.java
  src/main/java/sixgaezzang/sidepeek/users/dto/UserSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/UserSummaryResponse.java
  src/main/java/sixgaezzang/sidepeek/users/repository/UserRepository.java
  src/main/java/sixgaezzang/sidepeek/users/service/UserService.java
Labels: 🐛 아이고 벌레!, 🚀 더 만들어봤슈, 🥕 더 수정해봤슈

#46 컨트롤러 어드바이스 세팅
  src/main/java/sixgaezzang/sidepeek/common/exception/ErrorResponse.java
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/common/util/ValidationUtils.java
  src/main/java/sixgaezzang/sidepeek/users/domain/Password.java
  src/main/java/sixgaezzang/sidepeek/users/domain/User.java
Labels: 🚀 더 만들어봤슈

#43 회원가입 서비스 테스트 코드 작성
  build.gradle
  config/checkstyle/checkstyle.xml
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Labels: 🚀 더 만들어봤슈, ✅ 테스트해봤어유

#61 jacoco-report@v1.6 버전업!
  .github/workflows/ci.yml
Labels: 🐛 아이고 벌레!, ⚙️ 세팅했슈

#64 JWT 검증 로직 구현
  src/main/java/sixgaezzang/sidepeek/auth/jwt/JWTValidationFilter.java
  src/main/java/sixgaezzang/sidepeek/common/annotation/Login.java
  src/main/java/sixgaezzang/sidepeek/common/exception/GlobalExceptionHandler.java
  src/main/java/sixgaezzang/sidepeek/common/exception/InvalidAuthenticationException.java
  src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java
  src/main/java/sixgaezzang/sidepeek/config/SecurityConfig.java
  src/main/java/sixgaezzang/sidepeek/config/WebConfig.java
  src/main/resources/db/data/afterMigrate.sql
Labels: 🚀 더 만들어봤슈, 🌳 밥 좀 드셔유

#59 프로젝트 게시글 저장 api 구현
  src/main/java/sixgaezzang/sidepeek/auth/dto/response/LoginResponse.java
  src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java
  src/main/java/sixgaezzang/sidepeek/projects/controller/ProjectController.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/Project.java
  src/main/java/sixgaezzang/sidepeek/projects/domain/member/Member.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/MemberSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/request/ProjectSkillSaveRequest.java
  src/main/java/sixgaezzang/sidepeek/projects/dto/response/MemberSummary.java
  src/main/java/sixgaezzang/sidepeek/projects/service/FileService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/MemberService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectService.java
  src/main/java/sixgaezzang/sidepeek/projects/service/ProjectSkillService.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSearchResponse.java
  src/main/java/sixgaezzang/sidepeek/users/dto/response/UserSummary.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/sixgaezzang/sidepeek/users/service/UserServiceTest.java
Labels: 🚀 더 만들어봤슈, 🌳 밥 좀 드셔유

#68 access token 검증 기능 구현
  src/main/java/sixgaezzang/sidepeek/auth/controller/AuthController.java
  src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java
  src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java
Labels: 🚀 더 만들어봤슈, 🌳 밥 좀 드셔유

#69 Refresh / Access Token 재발급 기능 구현
  src/main/java/sixgaezzang/sidepeek/auth/controller/AuthController.java
  src/main/java/sixgaezzang/sidepeek/auth/dto/request/ReissueTokenRequest.java
  src/main/java/sixgaezzang/sidepeek/auth/service/AuthService.java
  src/main/java/sixgaezzang/sidepeek/auth/service/RefreshTokenService.java
  src/main/java/sixgaezzang/sidepeek/common/resolver/LoginUserArgumentResolver.java
  src/test/java/sixgaezzang/sidepeek/auth/service/AuthServiceTest.java
  src/test/java/sixgaezzang/sidepeek/auth/service/RefreshTokenServiceTest.java
Labels: 🚀 더 만들어봤슈
